# !pip install gym
# conda install -c conda-forge ffmpeg
# pip install pyglet
# import gym
# from gym import wrappers

# env = gym.make('CartPole-v0') # Create environment
# env = wrappers.Monitor(env, "./gym-results", force=True) # Create wrapper to display environment
# env.reset() # Reset environment

# # Run environment
# while True:
#     env.render() # Render environment
#     action = env.action_space.sample() # Get a random action
#     _, _, done, _ = env.step(action) # Take a step
#     if done: break # Break if environment is done

# env.close() # Close environment

# def show_replay():
#     """
#     Not-so-elegant way to display the MP4 file generated by the Monitor wrapper inside a notebook.
#     The Monitor wrapper dumps the replay to a local file that we then display as a HTML video object.
#     """
#     import io
#     import base64
#     from IPython.display import HTML
#     video = io.open('./gym-results/openaigym.video.%s.video000000.mp4' % env.file_infix, 'r+b').read()
#     encoded = base64.b64encode(video)
#     return HTML(data='''
#         <video width="360" height="auto" alt="test" controls><source src="data:video/mp4;base64,{0}" type="video/mp4" /></video>'''
#     .format(encoded.decode('ascii')))
    
# show_replay()