test1:

    n_envs: 128
    n_steps: 256
    epoch: 3
    mini_batch_per_epoch: 8
    mini_batch_size: 2048

    gamma: 0.99
    lmbda: 0.95
    learning_rate: 0.001
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.7
    entropy_coef: 0.01